### PR TITLE
Check `tlist` properties

### LINKED ISSUE #377: Incorrect return state and expectation value for time evolution solvers with trivial `tlist`
### Bug Description

Usually no one will specify `tlist = [0, 0]`, but somehow this is still a bug because the number of `states` and the values of `expect` will be incorrect.

### Code to Reproduce the Bug

```julia
tlist = [0, 0]
sol = sesolve(sigmax(), basis(2, 0), tlist)
println(sol.states, "\n")

sol = sesolve(sigmax(), basis(2, 0), tlist, e_ops = [sigmaz()])
println(sol.expect)
```

### Code Output

```shell
QuantumObject{KetQuantumObject, Dimensions{1, Tuple{Space}}, Vector{ComplexF64}}[
Quantum Object:   type=Ket   dims=[2]   size=(2,)
2-element Vector{ComplexF64}:
 1.0 + 0.0im
 0.0 + 0.0im]

ComplexF64[1.0 + 0.0im 6.93949973204724e-310 + 6.93949973206147e-310im]
```

### Expected Behaviour

```
QuantumObject{KetQuantumObject, Dimensions{1, Tuple{Space}}, Vector{ComplexF64}}[
Quantum Object:   type=Ket   dims=[2]   size=(2,)
2-element Vector{ComplexF64}:
 1.0 + 0.0im
 0.0 + 0.0im, 
Quantum Object:   type=Ket   dims=[2]   size=(2,)
2-element Vector{ComplexF64}:
 1.0 + 0.0im
 0.0 + 0.0im]

ComplexF64[1.0 + 0.0im 1.0 + 0.0im]
```

### Your Environment

```shell
Julia              Ver. 1.10.5
QuantumToolbox     Ver. 0.25.0
SciMLOperators     Ver. 0.3.12
LinearSolve        Ver. 2.38.0
OrdinaryDiffEqCore Ver. 1.12.1
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by albertomercurio**
## Checklist
Thank you for contributing to `QuantumToolbox.jl`! Please make sure you have finished the following tasks before opening the PR.

- [x] Please read [Contributing to QuantumToolbox.jl](https://qutip.org/QuantumToolbox.jl/stable/resources/contributing).
- [x] Any code changes were done in a way that does not break public API.
- [x] Appropriate tests were added and tested locally by running: `make test`.
- [x] Any code changes should be `julia` formatted by running: `make format`.
- [x] All documents (in `docs/` folder) related to code changes were updated and able to build locally by running: `make docs`.
- [x] (If necessary) the `CHANGELOG.md` should be updated (regarding to the code changes) and built by running: `make changelog`.

Request for a review after you have completed all the tasks. If you have not finished them all, you can also open a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to let the others know this on-going work.

## Description
I add some checks on the `tlist` argument. It throws an error if `tlist` is either empty, not sorted or containing repeated values.

## Related issues or PRs
Fixes #377

### CODE REVIEW

File: src/time_evolution/time_evolution.jl [hunk 1]
```diff
@@ -212,6 +212,19 @@ struct DiscreteLindbladJumpCallback <: LindbladJumpCallbackType end
 
 ContinuousLindbladJumpCallback(; interp_points::Int = 10) = ContinuousLindbladJumpCallback(interp_points)
 
+function _check_tlist(tlist, T::Type)
+    tlist2 = convert(Vector{T}, tlist) # Convert it to support GPUs and avoid type instabilities for OrdinaryDiffEq.jl
+
+    # Check if the list of times is not empty
+    isempty(tlist2) && throw(ArgumentError("The list of times must not be empty."))
+    # Check if the list of times is sorted
+    !issorted(tlist2) && throw(ArgumentError("The list of times must be sorted."))
```
Comment (ytdHuang) [inline src/time_evolution/time_evolution.jl:221]: a small suggestion here, I think:
```
The "time list" must ...
```
will be more straightforward because the argument name is `tlist`.

File: src/time_evolution/time_evolution.jl [hunk 2]
```diff
@@ -212,6 +212,19 @@ struct DiscreteLindbladJumpCallback <: LindbladJumpCallbackType end
...
+    # Check if the list of times is unique
+    length(tlist2) != length(unique(tlist2)) && throw(ArgumentError("The list of times must be unique."))
```
Comment (ytdHuang) [inline src/time_evolution/time_evolution.jl:223]: how about we just use `allunique`, like:
```suggestion
    allunique(tlist2) || throw(ArgumentError("The time list must be unique."))
```

In this case, I think it won't need extra allocations ?

File: test/core-test/time_evolution.jl [hunk 3]
```diff
@@ -63,14 +63,21 @@
...
+
         @testset "Memory Allocations" begin
             allocs_tot = @allocations sesolve(H, ψ0, tlist, e_ops = e_ops, progress_bar = Val(false)) # Warm-up
             allocs_tot = @allocations sesolve(H, ψ0, tlist, e_ops = e_ops, progress_bar = Val(false))
             @test allocs_tot < 150
 
             allocs_tot = @allocations sesolve(H, ψ0, tlist, saveat = [tlist[end]], progress_bar = Val(false)) # Warm-up
             allocs_tot = @allocations sesolve(H, ψ0, tlist, saveat = [tlist[end]], progress_bar = Val(false))
-            @test allocs_tot < 100
+            @test allocs_tot < 112
```
Comment (ytdHuang) [inline test/core-test/time_evolution.jl:80]: maybe we can rebase this part after using `allunique` in checking `tlist` ?

File: test/core-test/time_evolution.jl [hunk 4]
```diff
@@ -268,21 +288,21 @@
...
             allocs_tot = @allocations mesolve(L_td, ψ0, tlist, e_ops = e_ops, progress_bar = Val(false), params = p)
-            @test allocs_tot < 210
+            @test allocs_tot < 219
 
             allocs_tot =
                 @allocations mesolve(L_td, ψ0, tlist, progress_bar = Val(false), saveat = [tlist[end]], params = p) # Warm-up
             allocs_tot =
                 @allocations mesolve(L_td, ψ0, tlist, progress_bar = Val(false), saveat = [tlist[end]], params = p)
-            @test allocs_tot < 120
+            @test allocs_tot < 133
```
Comment (ytdHuang) [inline test/core-test/time_evolution.jl:305]: same here.

File: src/time_evolution/time_evolution.jl (hunk 1 above)
Comment (ytdHuang) [reply src/time_evolution/time_evolution.jl:221]: Also, we can also use

```
issorted(tlist2) ||
```

**Review by ytdHuang — APPROVED** [review]
